/* tslint:disable */

export enum RequestChunkContributionStateRequestState {
  STATE_UNDEFINED = "STATE_UNDEFINED",
  STATE_REQUEST_APPROVAL = "STATE_REQUEST_APPROVAL",
  STATE_REQUEST_PENDING = "STATE_REQUEST_PENDING",
}
