/* tslint:disable */

export enum RskPublicationType {
  PUBLICATION_TYPE_UNKNOWN = "PUBLICATION_TYPE_UNKNOWN",
  PUBLICATION_TYPE_RADIO = "PUBLICATION_TYPE_RADIO",
  PUBLICATION_TYPE_PODCAST = "PUBLICATION_TYPE_PODCAST",
  PUBLICATION_TYPE_PROMO = "PUBLICATION_TYPE_PROMO",
  PUBLICATION_TYPE_TV = "PUBLICATION_TYPE_TV",
  PUBLICATION_TYPE_OTHER = "PUBLICATION_TYPE_OTHER",
}
