/* tslint:disable */

export enum RsksearchContributionState {
  STATE_UNDEFINED = "STATE_UNDEFINED",
  STATE_REQUEST_APPROVAL = "STATE_REQUEST_APPROVAL",
  STATE_PENDING = "STATE_PENDING",
  STATE_APPROVED = "STATE_APPROVED",
  STATE_REJECTED = "STATE_REJECTED",
}
